apiVersion: v1
kind: Template
labels:
  template: devpi
metadata:
  name: devpi
  annotations:
    description: deploys devpi with nginx fronend and other relevant stuff
    tags: devpi, private-pypi, dev-pypi
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "devpi-db-storage-pvc"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "1Gi"
    volumeName: "${NAME}-db-storage"

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "${NAME}-file-storage-pvc"
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: "10Gi"
    volumeName: "devpi-file-storage"

- apiVersion: v1
  kind: Route
  metadata:
    name: "${NAME}-frontend"
  spec:
    host: "${FRONTEND_URL}"
    port:
      targetPort: 80
    to:
      kind: Service
      name: "nginx"

- apiVersion: v1
  kind: Service
  metadata:
    name: "nginx"
    annotations:
      description: waits for pypi requests and serves them
  spec:
    ports:
    - name: "http"
      port: 80
      targetPort: 80
    selector:
      name: "nginx"

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: nginx-configs
  data:
    nginx-devpi.conf: |
      server {
          server_name localhost $hostname "";
          listen 80;
          gzip             on;
          gzip_min_length  2000;
          gzip_proxied     any;
          gzip_types       text/html application/json;

          proxy_read_timeout 60s;
          client_max_body_size 64M;

          # set to where your devpi-server state is on the filesystem
          root /srv/devpi;


          # try serving static files directly
          location ~ /\+f/ {
              # workaround to pass non-GET/HEAD requests through to the named location below
              error_page 418 = @proxy_to_app;
              if ($request_method !~ (GET)|(HEAD)) {
                  return 418;
              }

              expires max;
              try_files /+files$uri @proxy_to_app;
          }
          # try serving docs directly
          location ~ /\+doc/ {
              try_files $uri @proxy_to_app;
          }
          location / {
              # workaround to pass all requests to / through to the named location below
              error_page 418 = @proxy_to_app;
              return 418;
          }
          location @proxy_to_app {
              proxy_pass http://$DEVPI_SERVICE_HOST:3141;
              proxy_set_header X-outside-url $scheme://$http_host;
              proxy_set_header X-Real-IP $remote_addr;
          }
      }

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: devpi-nginx

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "nginx"
    annotations:
      description: Deploys nginx pod and makes it use customized config and stored files
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ConfigChange
    replicas: 1
    selector:
      name: "nginx"
    template:
      metadata:
        name: "nginx"
        labels:
          name: "nginx"
      spec:
        securityContext: {}
        serviceAccount: devpi-nginx
        serviceAccountName: devpi-nginx
        containers:
        - name: nginx
          image: "nginx:latest"
          ports:
          - containerPort: 80
          readinessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: 80
          livenessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 30
            httpGet:
              # todo: update with better way to check health and readiness later
              path: /
              port: 80
          command: ['/bin/sh', '-c']
          args:
          - 'envsubst \$DEVPI_SERVICE_HOST < /conf/devpi.template > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
          volumeMounts:
          - mountPath: "/conf/"
            name: "nginx-conf"
          - mountPath: "/srv/devpi"
            name: "file-storage"
        volumes:
        - name: "nginx-conf"
          configMap:
            name: nginx-configs
            items:
            - key: nginx-devpi.conf
              path: devpi.template
        - name: "file-storage"
          persistentVolumeClaim:
            claimName: "${NAME}-file-storage-pvc"

- apiVersion: v1
  kind: Service
  metadata:
    name: "${NAME}"
    annotations:
      description: private pypi itself
  spec:
    ports:
    - name: "devpi-port"
      port: 3141
      targetPort: 3141
    selector:
      name: "${NAME}"

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${NAME}
    annotations:
      description: ""
      openshift.io/image.insecureRepository: "true"
  spec:
    lookupPolicy:
      local: true

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
    annotations:
      description: Building devpi image
      template.alpha.openshift.io/wait-for-ready: "true"
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "devpi:latest"
        #todo: add image update hooks
    source:
      type: Git
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      contextDir: ""
      images:
    triggers:
      - type: ConfigChange
    strategy:
      dockerStrategy:
        noCache: true
        env:
        - name: "GIT_SSL_NO_VERIFY"
          value: "true"

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${NAME}"
    annotations:
      description: ""
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ConfigChange
    replicas: 1
    selector:
      name: "${NAME}"
    template:
      metadata:
        name: "${NAME}"
        labels:
          name: "${NAME}"
      spec:
        containers:
        - name: ${NAME}
          image: "devpi:latest"
          ports:
          - containerPort: 3141
          readinessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: 3141
          livenessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 30
            httpGet:
              # todo: update with better way to check health and readiness later
              path: /
              port: 3141
          volumeMounts:
          - mountPath: "/srv/devpi"
            name: "file-storage"
        volumes:
        - name: "file-storage"
          persistentVolumeClaim:
            claimName: "${NAME}-file-storage-pvc"
      triggers:
      - type: ImageChange
      - type: ConfigChange

parameters:
- name: NAME
  required: true
  displayName: name which will be used everywhere to give objects names and add labels
  description: name which will be used everywhere to give objects names and add labels
  value: devpi

- name: SOURCE_REPOSITORY_URL
  required: true
  displayName: repo url with docker file
  description: repo url with docker file
  value: https://github.com/RonnyPfannschmidt-RedHat/devpi-cloud-deployments.git

- name: SOURCE_REPOSITORY_REF
  required: true
  displayName: branch
  description: branch
  value: master

- name: FRONTEND_URL
  required: true
  displayName: devpi url to expose
  description: devpi url to expose