apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: devpi
  name: devpi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: devpi
    spec:
      containers:
      - image: devpi
        name: devpi
        resources: {}
        volumeMounts:
        - mountPath: /srv/devpi
          name: devpi-files
      restartPolicy: Always
      volumes:
      - name: devpi-files
        persistentVolumeClaim:
          claimName: devpi-files
status: {}
